/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x40000000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_AD_B0_13 (coord J11), UART1_RXD/J11[2] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_AD_B0_12 (coord J12), UART1_TXD/J13[2] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_SD_B0_00 (coord H3), J17[6]/U63[8] */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_SD_B0_00_PERIPHERAL                             PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_SD_B0_00_SIGNAL                                    A   /*!< Signal name */
#define BOARD_INITPINS_GPIO_SD_B0_00_CHANNEL                                  0U   /*!< Signal channel */

/* GPIO_SD_B0_02 (coord J3), J17[4]/U64[8] */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_SD_B0_02_PERIPHERAL                             PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_SD_B0_02_SIGNAL                                    A   /*!< Signal name */
#define BOARD_INITPINS_GPIO_SD_B0_02_CHANNEL                                  1U   /*!< Signal channel */

/* GPIO_B0_06 (coord B8), LCDIF_D2/J49[A26]/BT_CFG[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D2_PERIPHERAL                                  PWM2   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D2_SIGNAL                                         A   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D2_CHANNEL                                       0U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
